# sudo: false

language: cpp

# addons:
#   apt:
#     packages:
#       - gcc-arm-none-eabi

before_script:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-none-eabi

script:
  - cd firmware/
  - make
