language: cpp

cache: apt

notifications:
  irc:
    channels:
      - "chat.freenode.net#portapack"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      # TODO: The "build_number.1" in this URL is almost certainly wrong, but correct value not available from Travis?
      - "Firmware download : https://portapack-h1-builds.s3.amazonaws.com/%{repository_slug}/%{build_number}/%{build_number}.1/build/firmware/portapack-h1-firmware-%{commit}.tar.bz2"

before_script:
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 -O /tmp/gcc-arm.tar.bz2
  - tar -xf /tmp/gcc-arm.tar.bz2
  - export PATH=$PWD/gcc-arm-none-eabi-6-2017-q2-update/bin:$PATH
  - export CC="arm-none-eabi-gcc"
  - export CXX="arm-none-eabi-g++"

script:
  # TODO: Introduce top-level Makefile, this is lame.
  - mkdir build/
  - pushd build/
  - cmake ..
  - make release
  - popd

addons:
  apt:
    packages:
      - lib32bz2-1.0
      - lib32ncurses5
      - lib32z1
      - cmake
    sources:
      - kalakris-cmake
  artifacts:
    paths:
      - $(ls build/firmware/portapack-h1-havoc-*.tar.bz2 | tr "\n" ":")
      - $(ls build/firmware/portapack-h1-havoc-*.zip | tr "\n" ":")
