# sudo: false

language: cpp

# addons:
#   apt:
#     packages:
#       - gcc-arm-none-eabi

cache: apt

before_install:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-none-eabi

before_script:
  - export CC="arm-none-eabi-gcc"
  - export CXX="arm-none-eabi-g++"

script:
  - cd firmware/
  - make
